#!/usr/bin/env bash

# Clear all aliases
unalias -a

# Fix my ls options
eval `dircolors -b ~/.dir_colors`           # -b for bash
export LS_OPTIONS=" -CF -SX -b -T 0"
if [ "$TERM" == "dumb" ] ; then LS_OPTIONS=" --color=none $LS_OPTIONS" ; else LS_OPTIONS=" --color=auto $LS_OPTIONS" ; fi
alias ls='ls $LS_OPTIONS'

# Fix my less options
export LESS="-eFXir"                 # -r means 'show raw ctrl chars' -- makes output colored
alias more=less

# cap1 works better with current (2008Jan) rails
alias cap1="`which cap` _1.4.1_"
# pretty ruby dox
export RI='-f ansi'

alias gemdocs="gem server >/dev/null 2>&1 & sleep 0.2 ; open http://localhost:8808"


####################### Configure Commands########################

# Other Env Vars
export PWD DISPLAY

# Tell CVS where it lives
export CVSROOT=:ext:mrflip@cvs.hola.sourceforge.net:/cvsroot/hola
export CVS_RSH=ssh
export RSYNC_RSH=ssh

# This changes the output of the "time" builtin
# grep for TIMEFORMAT in man bash
export TIMEFORMAT=$'\nreal\t%3lR\tuser\t%3lU\tsys\t%3lS\tpct\t%P'

