#!/usr/bin/env bash

# Clear all aliases
unalias -a

if [ "$MACHINE" == "OSX" ] && [ -d /usr/local/.git ] ; then
  brew_prefix=/usr/local
  source $HOME/.bash/brew_aliases
  unalias printf # leave it at the system one
fi

# Fix my ls options
if [ -z `which dircolors` ] ; then false ; else
  eval `dircolors -b ~/.dir_colors`           # -b for bash
fi 
export LS_OPTIONS=" -CF "
if `ls --help 2>/dev/null | grep -q gnu` ; then
  LS_OPTIONS="$LS_OPTIONS -SX -b -T 0"
  if [ "$TERM" == "dumb" ] ; then false ; else LS_OPTIONS=" --color=auto $LS_OPTIONS" ; fi
fi
alias ls='ls $LS_OPTIONS'

# Fix my less options
export LESS="-eFXir"                 # -r means 'show raw ctrl chars' -- makes output colored
alias more=less

# pretty ruby dox
export RI='-f ansi'

alias gemdocs="gem server >/dev/null 2>&1 & sleep 0.2 ; open http://localhost:8808"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias whois="whois -h whois-servers.net"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Start an HTTP server from a directory
alias server="open http://localhost:8080/ && python -m SimpleHTTPServer 8080"

# Show/Hide hidden files in Finder
alias finder_hidden_show="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
alias finder_hidden_hide="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

# Show/Hide all desktop icons (useful when presenting)
alias finder_desktop_show="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias finder_desktop_hide="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# emacs from the commandline
alias emacs="/usr/local/Cellar/emacs/HEAD/Emacs.app/Contents/MacOS/Emacs -nw"

####################### Configure Commands########################

# Other Env Vars
export PWD DISPLAY

# Tell CVS where it lives
export CVSROOT=:ext:mrflip@cvs.hola.sourceforge.net:/cvsroot/hola
export CVS_RSH=ssh
export RSYNC_RSH=ssh

# This changes the output of the "time" builtin
# grep for TIMEFORMAT in man bash
export TIMEFORMAT=$'\nreal\t%3lR\tuser\t%3lU\tsys\t%3lS\tpct\t%P'

# misc
alias reload='. ~/.bash_profile'
