#!/usr/bin/env bash
  
  # ###### History ########################################
  set   +o history
  export HISTFILE=$HOME/.history-bash/"hist-`date +%Y-%W`.hist"  # No ~ here
  export HISTCONTROL=ignoreboth
  if [[ ! -f $HISTFILE ]]; then
    LASTHIST=~/.history-bash/`/bin/ls -1tr ~/.history-bash/ | tail -n 1`; 
    if [[ -f "$LASTHIST" ]]; then
        tail -n 1000 "$LASTHIST" > $HISTFILE 
        # Write a divider to identify where the prior day's session history ends
        echo "####### `date +%Y-%W-%w` : `date` #######" >> $HISTFILE
    fi
  fi
  export HISTSIZE=10000
  history  -n $HISTFILE
  set    -o history
  unset  HISTFILESIZE
  export HISTIGNORE="ls:[bf]g:exit: *:history:histgrep:&"   # & means consec. duplicates
  alias  histup='history -a $HISTFILE'
  export histchars=""
  
  ####################### Shell Stuff ##############################
  
  umask 022 					# readable by all / writeable only by me
  ulimit -S -c 0				# Turn off core dumps
  # ulimit -S -n 2048				# cure problems with too few file handles.  max is 10240
  
  # Bash Config
  shopt -s cmdhist histappend histverify 
  shopt -s checkwinsize cdspell 
  shopt -s nocaseglob                             # good for non-case-sensitive os
  set   -o ignoreeof 				# don't log out if I hit ^-D
  
  ###### I18n ###########################################
  
  export FIGNORE="~"
  export BASH_ENV=$HOME/.bashrc
  export LANG=en_US.UTF-8
  export LC_CTYPE=en_US.UTF-8
  export LC_NUMERIC="en_US.UTF-8"
  export LC_TIME="en_US.UTF-8"
  export LC_COLLATE="en_US.UTF-8"
  export LC_MONETARY="en_US.UTF-8"
  export LC_MESSAGES="en_US.UTF-8"
  export LC_PAPER="en_US.UTF-8"
  export LC_NAME="en_US.UTF-8"
  export LC_ADDRESS="en_US.UTF-8"
  export LC_TELEPHONE="en_US.UTF-8"
  export LC_MEASUREMENT="en_US.UTF-8"
  export LC_IDENTIFICATION="en_US.UTF-8"
  
  # Set the command line editor to emacs.
  set -o emacs
  export FCEDIT=emacs
  if [ "$DISPLAY" = "" ] ; then 
      export ALTERNATE_EDITOR=emacs EDITOR=nano VISUAL=nano
  else
    export ALTERNATE_EDITOR=emacs EDITOR=emacsclient VISUAL=emacsclient
  fi
