#!/usr/bin/env bash

####################### Shell Stuff ##############################


umask 022 					# readable by all / writeable only by me
ulimit -S -c 0					# Turn off core dumps
ulimit -S -n 2048				# cure problems with too few file handles.  max is 10240

###
#
# Wield Infinite Monkeywrench
export IMW_ROOT=$HOME/ics
export PATH=$IMW_ROOT/imw/bin:$PATH
export RUBYLIB=$IMW_ROOT/imw/lib:$RUBYLIB
export GEM_PATH=/usr/local/lib/ruby/gems/1.8:/Library/Ruby/Gems/1.8/:/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/1.8/
export RUBY_SOURCE_DIR=/usr/local/bin/ruby

# Bash Config
shopt -s cmdhist histappend histverify 
shopt -s checkwinsize cdspell 
shopt -s nocaseglob                             # good for non-case-sensitive os
set   -o ignoreeof 				# don't log out if I hit ^-D

###### History ########################################
set   -o history
export HISTFILE=$HOME/.history-bash/"hist-`date +%Y-%W`.hist"  # No ~ here
export HISTCONTROL=ignoreboth
if [[ ! -f $HISTFILE ]]; then
LASTHIST=~/.history-bash/`ls -1tr ~/.history-bash/ | tail -1`; 
if [[ -f "$LASTHIST" ]]; then
    tail -500 "$LASTHIST" > $HISTFILE 
    # Write a divider to identify where the prior day's session history ends
    echo "####### `date +%Y-%W-%w` : `date` #######" >> $HISTFILE
fi
fi
history -n $HISTFILE
export HISTSIZE=10000
unset  HISTFILESIZE
export HISTIGNORE="ls:[bf]g:exit: *:history:histgrep:&"   # & means consec. duplicates
alias  histup='history -n $HISTFILE'
export histchars=""

###### I18n ###########################################

export FIGNORE="~"
export BASH_ENV=$HOME/.bashrc
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"

# Set the command line editor to emacs.
set -o emacs                
export FCEDIT=emacs
export VISUAL=emacs
export EDITOR=nano
export EDITOR="mate -w"

#
# give me back my ^Q, ^S keys, etc.  you can check things with "stty -e"
#   discard "" dsusp ""   eof ""     eol ""     eol2 ""    erase ""   intr ""    kill ""    lnext ""
#   ^@         ^Y         ^D         <undef>    <undef>    ^?         ^C         ^@         ^@
#   min ""     quit ""    reprint "" start ""   status ""  stop ""    susp ""    time ""    werase ""
#   1          ^\         ^@         ^@         ^@         ^@         ^Z         0          ^@
# 
# lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
#         -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
#         -extproc
# iflags: -istrip icrnl -inlcr -igncr -ixon -ixoff -ixany imaxbel -ignbrk
#         brkint -inpck ignpar -parmrk
# oflags: opost onlcr -oxtabs -onocr -onlret
# cflags: cread cs8 -parenb -parodd -hupcl -clocal -cstopb -crtscts
#         -dsrflow -dtrflow -mdmbuf
stty -ixon -ixoff flush "" rprnt "" kill ""  lnext "" start "" stop "" werase ""
# stty erase  
