#!/usr/bin/env bash

if    uname -a | egrep 'Darwin.*9\.[6789]' > /dev/null 2>&1 ; then
  export MACHINE=OSX
elif uname -a | egrep '^Linux' > /dev/null 2>&1 ; then
  # grep -i ubuntu /etc/issue 
  export MACHINE=LINUX
fi

# define append_path and prepend_path to add directory paths, e.g. PATH, MANPATH.
# add to end of path
append_path()
{
  if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
    eval "$1=\$$1:$2"
  fi
}

# add to front of path
prepend_path()
{
  if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
    eval "$1=$2:\$$1"
  fi
}

###########################################################################
#
# PATH
#
export PATH_HOME=$HOME/bin:$HOME/slice/bin
export PATH_LOCL=/usr/local/bin
export MPTH_LOCL=/usr/local/man
export CORE_PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/X11/bin:/usr/X11R6/bin
export OSX_PATH=/Applications/MAMP/Library/bin:/usr/local/git/bin
export OSX_MPTH=/sw/share/man:/Applications/MAMP/Library/man
export LINUX_PATH=/public/bin
export LINUX_MPTH=/public/man:/opt/local/man

export PATH
export MANPATH=${MANPATH-/usr/local/man}
PATH=$PATH_LOCL:$PATH
if   [ "$MACHINE" == "OSX" ] ; then
  append_path  PATH    $OSX_PATH ;
  append_path  MANPATH $OSX_MPTH ;
  prepend_path PATH    /sw/bin   ;
elif [ "$MACHINE" == "Linux" ] ; then
  append_path PATH    $LINUX_PATH ;
  append_path MANPATH $LINUX_MPTH ;
fi
prepend_path MANPATH $MPTH_LOCL
PATH=$PATH_HOME:$PATH

PKG_CONFIG_PATH_OSX="/sw/lib/pkgconfig:/sw/share/pkgconfig"
PKG_CONFIG_PATH_MATH="/public/lib/pkgconfig:/public/share/pkgconfig"

# Use the ruby in /usr/local
# export GEM_PATH=/usr/local/lib/ruby/gems/1.8:/Library/Ruby/Gems/1.8/:/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/1.8/
# export RUBY_SOURCE_DIR=/usr/local/bin/ruby
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:$PKG_CONFIG_PATH_OSX:$PKG_CONFIG_PATH_MATH:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/X11R6/lib/pkgconfig"
# export PERL5LIB=/public/share/perl/lib:/public/share/perl:/usr/local/lib/perl5/site_perl:/usr/share/perl/:/usr/lib/perl:/usr/lib/perl5
export RUBYLIB=$HOME/.rubylib
export WUKONG_PATH=${HOME}/ics/wukong/lib:${HOME}/ics/wuclan/lib:${HOME}/ics/monkeyshines/lib

###########################################################################
#
# Amazon EC2 Setup
#


###########################################################################
#
# Amazon EC2 Setup
#
#
# In order to communicate with AWS/EC2/S3 stuff first make sure you
# have a valid AWS account (we do, it's aws@infochimps.org), make sure
# we've signed up for the corresponding service (we have for EC2 &
# S3), and make sure we've put in a credit card (we have).
#

export AWS_ACCOUNT_ID='484232731444'
export AWS_ACCESS_KEY_ID=02S6Y1EFA7ZZ7KCZH3G2
export EC2_PRIVATE_KEY=${HOME}/.hadoop-ec2/certs/pk.pem
export EC2_CERT=${HOME}/.hadoop-ec2/certs/cert.pem
export EC2_HOME=/usr/local/share/ec2-api-tools

if   [ "$MACHINE" == "OSX" ] ; then
  export JAVA_HOME=${JAVA_HOME-/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home}
  export EC2_AMITOOL_HOME=/usr/local/share/ec2-ami-tools
  export HADOOP_HOME=${HADOOP_HOME-/usr/local/share/hadoop}
  export PIG_HOME=${PIG_HOME-/usr/local/share/pig}
  append_path PATH $EC2_AMITOOL_HOME/bin
elif [ "$MACHINE" == "Linux" ] ; then
  export HADOOP_HOME=${HADOOP_HOME-/usr/lib/hadoop/}
  # export PIG_HOME=${PIG_HOME-/usr/local/share/pig}
  # On linux, it's installed via apt, so lives in /usr/bin/...
  export JAVA_HOME=${JAVA_HOME-/usr/lib/jvm/java-6-sun/jre}
fi
append_path PATH $EC2_HOME/bin
append_path PATH $EC2_AMITOOL_HOME/bin
append_path PATH $JAVA_HOME/bin

# Location of EC2 keys.
export EC2_KEYPAIR_DIR=`dirname "$EC2_PRIVATE_KEY"`
export EC2_KEYPAIR_NAME=gibbon
export EC2_KEYPAIR_FILE="${EC2_KEYPAIR_DIR}/${EC2_KEYPAIR_NAME}.pem"
export EC2_SSH_OPTIONS="-i ${EC2_KEYPAIR_FILE} -o StrictHostKeyChecking=no -o ServerAliveInterval=30"
export SSH_OPTS=$EC2_SSH_OPTIONS  
