#!/usr/bin/env bash

###########################################################################
#
# PATH
#
MAC_PATH=/sw/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
PATH_HOME=$HOME/bin:$HOME/slice/bin
PATH_LOCL=/usr/local/bin
MPTH_LOCL=/usr/local/man
PATH_MAMP=/Applications/MAMP/Library/bin
MPTH_MAMP=/Applications/MAMP/Library/man

export PATH=$PATH_HOME:$PATH_LOCL:$PATH:$PATH_MAMP:$MAC_PATH
export         MANPATH=$MPTH_LOCL:$MANPATH

export PKG_CONFIG_PATH="/usr/local/share/pkgconfig:/sw/share/pkgconfig:/usr/local/lib/pkgconfig:/sw/lib/pkgconfig:/usr/X11R6/lib/pkgconfig"

if uname -a | egrep 'Darwin.*9\.6' > /dev/null 2>&1 ; then
    export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
fi
