#!/usr/bin/env bash

############################## Set Prompt  ##############################
export PR_TITLE='\[\033]0;\h:\w $(parse_git_branch)\007\]'
export PR_PROMPT='\[\033[0;36m\]'$HOSTNAME' \[\033[0;32m\]\w\[\033[0;37;40m\]$ '
export  PR_WHITE='\[\033[0;34m\]'$HOSTNAME' \[\033[0;32m\]\w\[\033[0;30;47m\] '
export PR_PROMPT2='\[\033[0;36m\]cont... \[\033[1;36m\]>\[\033[0;37m\]$ '

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(branch: \1)/'
}

if [ "$0" = "sh" ] ; then
  PS1="$HOSTNAME (sh) $ "
  PS2="cont... > "
else
  case ${TERM-NONE} in
    mrxvt|xterm|rxvt|xterm-color)
      PS1=${PR_TITLE}${PR_PROMPT}
      PS2=${PR_TITLE}${PR_PROMPT2}
      ;;
    dumb)
      # keep it simple (probably emacs)
      export PS1="\h \w$ "
      export PS2='\w cont...\$ '
      ;;
    NONE)
      if [ -z "$DISPLAY" ] ; then
        # I have a $DISPLAY set, so assume xterm...
        PS1=${PR_TITLE}${PR_PROMPT}
        PS2=${PR_TITLE}${PR_PROMPT2}
      else
        # keep it simple (probably emacs)
        export PS1="\h \w$ "
        export PS2='\w cont...\$ '
      fi
      ;;
  esac
fi
